name: testing github action
'on': push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "Hello world"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config --global user.name "Arun1102"
          git config --global user.email "arunattappan@gmail.com"
      - name: Push to another repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          TOKEN_GIT: ${{ secrets.TOKEN_GIT }} 
        with:
          source_file: 'text'
          destination_repo: 'Arun1102/MainRepo'
          destination_folder: 'test-dir' # optional
          user_email: 'arunattappan@gmail.com' # your email
          user_name: 'Arun1102'           # your login
          commit_message: 'A custom message for the commit'
