name: Sync source repository to target folders

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        repository: Arun1102/test1

    - name: Print hello world
      id: print
      run: echo "hello world"

    - name: Set up Git
      run: |
        git config --global user.name "Arun1102"
        git config --global user.email "arunattappan@gmail.com"

    - name: Clone target repository
      if: ${{ steps.print.outcome == 'success' }}
      run: |
        git clone https://github.com/Arun1102/MainRepo.git
      env:
        TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}

    - name: List root folders from target repository
      id: list_folders
      run: |
        # Find all root-level directories in the target repository
        root_folders=$(find MainRepo -mindepth 1 -maxdepth 1 -type d -not -name '.git' -not -name 'MainRepo' -not -name '.github')
        echo "Root folders found: $root_folders"
        echo "::set-output name=folders::$root_folders"

    - name: Debug folder paths
      run: |
        echo "Folders to sync:"
        echo "${{ steps.list_folders.outputs.folders }}"

    - name: Sync source repository to each target folder
      run: |
        # Convert the list of root folders to an array
        IFS=$'\n' read -d '' -r -a folders <<< "${{ steps.list_folders.outputs.folders }}"

        # Print each folder path for debugging
        for folder in "${folders[@]}"; do
          echo "Syncing source repository to $folder"
          echo "Folder exists: $(ls -ld "$folder")"
          rsync -av --exclude='.git' --exclude='MainRepo' --exclude='.github' ./ "$folder/"
        done

    - name: Commit and push to target repository
      run: |
        cd MainRepo
        git add .
        git commit -m "Sync source repo to all root folders"
        git push https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@github.com/Arun1102/MainRepo.git
      env:
        TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
