name: testing github action

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        path: './'
        repository: 'Arun1102/test1'
        token: ${{ secrets.TARGET_REPO_PAT }}
        fetch-depth: 0
        persist-credentials: true

    - name: Copy common files to new Repo
      shell: bash
      run: |
          rsync -av --exclude='.git' --exclude='MainRepo' --exclude='README.md' --exclude='text' --exclude='.github' ./ "company A"

    - name: Check for new files
      id: newFiles
      shell: bash
      working-directory: ./
      run: |
        git add -A
        git status --porcelain | wc -l
        if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
          echo "::set-output name=hasNewFiles::true"
        else
          echo "::set-output name=hasNewFiles::false"
        fi

    - name: Push new files
      if: ${{ steps.newFiles.outputs.hasNewFiles == 'true' }}
      shell: bash
      working-directory: 'company A'
      run: |
        git config --global user.name "Arun1102"
        git config --global user.email "arunattappan@gmail.com"
        git add -A
        git commit -m "commited"
        git push
