name: Copy Resources from One Repo to Another

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the source repository (current repo)
    - name: Checkout source repository
      uses: actions/checkout@v3

    # Step 2: Checkout the target repository using a deploy key or personal access token
    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: Arun1102/MainRepo  # Target repo in format username/repo
        token: ${{ secrets.TARGET_REPO_PAT }}  # You can use a PAT in GitHub Secrets for access
        path: target-repo-folder            # Path to checkout the target repo

    # Step 3: Copy files from source to target repository
    - name: Copy files to target repository
      run: |
        cp -R ./src/ ./target-directory/

    
    # Step 4: Commit and push the changes to the target repository
    - name: Commit and push changes
      run: |
        cd target-repo-folder
        git config --global user.name "Arun1102"
        git config --global user.email "arunattappan@gmail.com"
        git add .
        git commit -m "Sync resources from source repo"
        git push origin main

